### ISSUE TITLE
Where to download a (usable) monaco build for a specific TypeScript version?

### ISSUE THREAD

**Issue by AlCalzone** [orta/make-monaco-builds#4]
I'm not sure if this is the correct repo to ask this question, but it seemed like it.

In https://github.com/iobroker/iobroker.javascript we use the monaco editor to power the JS and TS editing experience. I'd like to keep a bit more up to date with TypeScript, but to me the versions of monaco-editor are a bit like a black box. Is there any way to get working monaco builds for a specific TS version, say 3.7.x?

**Comment by orta** [comment]
Roughly: The TypeScript version in monaco comes through monaco-typescript, which embed typescript. This repo automates all that process for specific TS versions.

You can use our versions of monaco-editor which are tied specifically to their typescript version: https://www.npmjs.com/package/@typescript-deploys/monaco-editor

You might also be interested in http://www.typescriptlang.org/v2/dev/sandbox/

**Comment by AlCalzone** [comment]
Thanks, I'll check it out!
